// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCRel1Change();
void onCRel2Change();
void onCHeatChange();
void onTMaxChange();
void onTMinChange();

float c_temperature;
float c_humidity;
int c_moisture;
int c_people;
bool c_pir;
bool c_rel_1;
bool c_rel_2;
int c_heat;
int t_max;
int t_min;

void initProperties(){

  ArduinoCloud.addProperty(c_temperature, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(c_humidity, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(c_moisture, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(c_people, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(c_pir, READ, 1 * SECONDS, NULL);

  ArduinoCloud.addProperty(c_rel_1, READWRITE, ON_CHANGE, onCRel1Change);
  ArduinoCloud.addProperty(c_rel_2, READWRITE, ON_CHANGE, onCRel2Change);
  ArduinoCloud.addProperty(c_heat, READWRITE, ON_CHANGE, onCHeatChange);

  ArduinoCloud.addProperty(t_max, READWRITE, ON_CHANGE, onTMaxChange);
  ArduinoCloud.addProperty(t_min, READWRITE, ON_CHANGE, onTMinChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
